# TODO:
# - AppImage for GNU/Linux distributions
# - DiskImage for MacOS 
# - Regular Zip for Windows

name: "John's Adventure Release"

on:    
  workflow_dispatch:

env:
  VERSION: 1.2
  GAME_TITLE: Johns Adventure (Chapter 1)
  
jobs:
  gnu-linux:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pyinstaller
        pip install pygame --pre
        
    - name: Build game 
      run: |
        pyinstaller build.spec
        chmod +x ./dist/*
        
    - name: Install Zip package
      uses: montudor/action-zip@v1.0.0
    
    - name: Start zipping 
      run: |
        zip "Johns Adventure (Chapter 1) GNU/Linux.zip" ./dist/*
    
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.3.9
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: ./*.zip
        branches: main
        # With verbose: true, be verbose.
        verbose: true
        # Set custom tag name.
        tag_name: ${{ env.GAME_TITLE }} ${{ env.VERSION }}

